const $ = (id) => document.getElementById(id);
const request = (url, options = {}) => fetch(`/api${url}`, {headers: {'Content-Type': 'application/json'}, ...options}).then(async (r) => { const data = await r.json(); if (!r.ok) throw new Error(data.error); return data; });
const status = (message) => $('status').textContent = message;
async function loadHistory() { const data = await request('/transactions'); $('history').innerHTML = data.transactions.map(t => `<li>${t.tx_id}: ${t.amount} to ${t.receiver} <button data-tx="${t.tx_id}">Proof</button></li>`).join(''); const tree = await request('/tree'); const width = Math.max(640, tree.layers[0]?.length * 90 || 640); $('tree').setAttribute('viewBox', `0 0 ${width} ${Math.max(120, tree.layers.length * 70)}`); $('tree').innerHTML = tree.layers.map((layer, level) => layer.map((hash, i) => `<g transform="translate(${(i + .5) * width / layer.length},${(level + .5) * 70})"><circle r="18"></circle><title>${hash}</title><text text-anchor="middle" dy="4">${hash.slice(0, 6)}</text></g>`).join('')).join(''); }
$('login').onclick = async () => { try { await request('/auth/login', {method:'POST', body: JSON.stringify({email:$('email').value,password:$('password').value})}); $('auth').hidden=true; $('ledger').hidden=false; await loadHistory(); } catch (e) { status(e.message); } };
$('register').onclick = async () => { try { await request('/auth/register', {method:'POST', body: JSON.stringify({email:$('email').value,password:$('password').value})}); status('Registered; please log in.'); } catch (e) { status(e.message); } };
$('logout').onclick = async () => { await request('/auth/logout', {method:'POST'}); location.reload(); };
$('transaction').onsubmit = async (e) => { e.preventDefault(); try { await request('/transactions', {method:'POST', body: JSON.stringify({receiver:$('receiver').value,amount:$('amount').value})}); e.target.reset(); await loadHistory(); } catch (err) { status(err.message); } };
$('history').onclick = async (e) => { if (e.target.dataset.tx) $('proof').textContent = JSON.stringify(await request(`/proof/${e.target.dataset.tx}`), null, 2); };
